In [200]:
import torch as t

# I. Introduction to Tensors

## 1. Creating Tensors

#### A. Scalar

In [142]:
scalar = t.tensor(7)
scalar

tensor(7)

In [143]:
print(scalar.item())  # .item() only available for scalar
scalar.ndim

7


0

#### B. Vector

In [144]:
vector = t.tensor([7, 7])
vector

tensor([7, 7])

In [145]:
vector.ndim  # number of square bracket

1

In [146]:
vector.shape

torch.Size([2])

#### C. MATRIX

In [147]:
matrix = t.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [148]:
matrix.ndim

2

In [149]:
matrix.shape

torch.Size([2, 2])

#### D. TENSOR

In [150]:
tensor = t.tensor([[[1, 2, 3], [4, 5, 6], [8, 9, 10]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 8,  9, 10]]])

In [151]:
tensor.ndim

3

In [152]:
tensor.shape  # 1 3x3 matrix

torch.Size([1, 3, 3])

#### E. Random tensors

In [199]:
random_tensor = t.rand(3, 4)
random_tensor

tensor([[0.8645, 0.6934, 0.9721, 0.2847],
        [0.7271, 0.2335, 0.5542, 0.2804],
        [0.6489, 0.8179, 0.9999, 0.8257]])

In [154]:
random_image_tensor = t.rand(size=(3, 224, 224))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#### E. Zeros and ones

In [155]:
# Create a tensor of full zeros
zeros = t.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [156]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [157]:
ones = t.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### F. Range of tensors and tensors-like

In [158]:
# use torch.range() will get a deprecated message, use torch.arange() instead
one_to_ten = t.arange(start=1, end=11, step=1)  # out: start -> (end-1)
print(one_to_ten)
print(one_to_ten.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([10])


In [159]:
ten_zeros = t.zeros_like(one_to_ten)
print(ten_zeros)
print(ten_zeros.shape)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([10])


## 2. Tensor datatypes
float32, float16, float64, etc...
This is a number of memory of a single number was stored in RAM

In [160]:
float_32_tensor = t.tensor([3.0, 6.0, 9.0],
                           dtype=None,  # What dtype is the tensor
                           device=None,  # What device of your tensor on
                           requires_grad=False)  # Whether or not to track gradients with this tensor operation
float_32_tensor.dtype

torch.float32

In [161]:
float_16_tensor = t.tensor([3.0, 6.0, 9.0], dtype=t.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [162]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [163]:
(float_16_tensor + float_32_tensor).dtype

torch.float32

In [164]:
int_32_tensor = t.tensor([3, 6, 9], dtype=t.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [165]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## 3. Getting information from tensor

In [166]:
some_tensor = t.rand(3, 4, 5)
some_tensor

tensor([[[7.0585e-01, 6.7942e-01, 8.4411e-01, 7.7608e-01, 6.7320e-01],
         [7.3394e-01, 7.1889e-01, 7.5331e-02, 1.3185e-01, 4.4097e-01],
         [1.3134e-02, 3.4005e-01, 5.9041e-01, 5.3109e-01, 6.2595e-02],
         [9.5354e-01, 9.8727e-01, 1.3013e-01, 5.0758e-01, 9.2108e-01]],

        [[4.1400e-01, 2.6117e-01, 5.9900e-01, 8.1109e-01, 7.1254e-01],
         [9.4071e-01, 6.1192e-02, 1.1321e-01, 8.1438e-04, 2.7645e-01],
         [2.4787e-01, 9.1228e-01, 8.9303e-01, 6.7247e-01, 7.2331e-01],
         [9.8234e-01, 4.7248e-02, 8.7259e-01, 3.1503e-01, 5.6165e-01]],

        [[7.1999e-01, 7.3840e-01, 2.1087e-01, 1.9495e-01, 8.6798e-01],
         [1.0011e-01, 9.9222e-01, 3.1475e-01, 7.4038e-01, 1.8544e-01],
         [6.0585e-01, 6.4331e-01, 1.3621e-01, 9.9489e-01, 4.5644e-01],
         [4.5280e-01, 7.6529e-01, 6.9654e-01, 9.7367e-01, 5.4472e-01]]])

In [167]:
print(f"size or shape: {some_tensor.size()}")  # size of a tensor nrow, ncol, nz, etc... == sometensor.shape
print(f"dtype: {some_tensor.dtype}")
print(f"devive: {some_tensor.device}")

size or shape: torch.Size([3, 4, 5])
dtype: torch.float32
devive: cpu


## 4.  Manipulating tensor ( tensor operation )
Tensor operations include:
 1. addition
2. Subtraction
3. multiplication (element-wise)
4. Division 
5. Matrix multiplication

In [168]:
# addition
t1 = t.tensor([1, 2, 3])
t1 + 10

tensor([11, 12, 13])

In [169]:
# Multiplication
t1 * 10

tensor([10, 20, 30])

In [170]:
# Subtract
t1 - 10

tensor([-9, -8, -7])

In [171]:
# try out pytorch built-in func
add1 = t.add(t1, 10)
mul1 = t.mul(t1, 10)
sub1 = t.subtract(t1, 10)
for item in [add1, mul1, sub1]:
    print(item)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


### A. Matrix multiplication
#### two main way to performing multiplication in neural networks and DL:
   1. element-wise: matrix with scalar , must be same shape if matrix with matrix<br> 
   2. matrix multiplication (dot product) using <code>t.matmul(t1, t2)</code> or <code>t1 @ t2</code> : matrix with matrix 

#### There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
    * `(3,2) @ (3,2)` won't work
    * `(3,2) @ (2,3)` will work
    * `(2,3) @ (3,2)` will work
2. The resulting matrix has the shape of the **outer dimensions**
    * `(3,2) @ (2,3) -> (3, 3)` 
    * `(2,3) @ (3,2) -) (2, 2)` 

In [172]:
# Element-wise
t1 = t.rand(4, 3)
t2 = t.rand(4, 3)
print(f"Element wise: t1 * t2")
print("equal")
t1 * t2

Element wise: t1 * t2
equal


tensor([[0.7500, 0.0696, 0.2928],
        [0.1755, 0.6932, 0.1325],
        [0.5438, 0.0897, 0.5427],
        [0.2566, 0.3315, 0.0314]])

In [173]:
# Matrix multiplication
t1 = t.rand(3, 4)
t2 = t.rand(4, 3)

print(f"Matrix multiplication: t.matmul(t1,t2)")
print("equal")
t.matmul(t1, t2)

Matrix multiplication: t.matmul(t1,t2)
equal


tensor([[1.3191, 1.1874, 0.2975],
        [2.3005, 1.5606, 0.4939],
        [1.1651, 0.7288, 0.3029]])

In [174]:
tensor_A = t.rand(2, 3)
tensor_A

tensor([[0.3492, 0.0546, 0.3584],
        [0.0342, 0.9312, 0.1468]])

In [175]:
tensor_A.T

tensor([[0.3492, 0.0342],
        [0.0546, 0.9312],
        [0.3584, 0.1468]])

### B. Fiding the min, max, mean, sum, etc... ( tensor aggregation )

In [176]:
x = t.arange(1, 100, 10)

# Min
t.min(x), x.min()

(tensor(1), tensor(1))

In [177]:
# Max
t.max(x), x.max()

(tensor(91), tensor(91))

In [178]:
# Mean. mean require a tensor of float32 dtype to work
t.mean(x.type(t.float32)), x.type(t.float32).mean()

(tensor(46.), tensor(46.))

In [179]:
# Sum
t.sum(x), x.sum()

(tensor(460), tensor(460))

In [180]:
# argmin: If there are multiple minimal values then the indices of the first minimal value are returned.
t.argmin(x), x[x.argmin()]

(tensor(0), tensor(1))

In [181]:
# argmax
t.argmax(x), x[x.argmax()]

(tensor(9), tensor(91))

### C. Reshaping, stacking, squeezing and unsqueezing tensors
1. Reshape - reshaping an input tensor to a defines shape
2. View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
3. Stacking - combine multiples tensors on top of each others
4. Squeeze - remove all 1 dimensions from a tensor
5. Unsqueeze - Add 1 dimensions to a target tensor
6. Permute - return a view of the input with dimension permuted (swapped) in a certain ways

In [182]:
x = t.arange(1.0, 11.0)
x, x.size()

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [183]:
# add an extra dim
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [184]:
# add an extra dim but use view, saving mem 
z = x.view(2, 5)
z, z.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [185]:
# stack tensors on top of each others
x_stacked = t.stack([x, x, x, x],dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [186]:
x_reshaped = x_reshaped.reshape(1, 10)
x_reshaped, x_reshaped.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [187]:
# squeeze: remove all 1 dim from target tensor; ex: (1,1,1,9) -> (9)
x_reshaped.squeeze(), x_reshaped.squeeze().size()

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [188]:
x_squeeze = x_reshaped.squeeze()
print(x_squeeze, x_squeeze.size())

x_unsqueeze = x_squeeze.unsqueeze(dim=0)
print(x_unsqueeze, x_unsqueeze.size())

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])


In [201]:
t.manual_seed(23)

# permute: re-arrange the dimension of target tensor in a specific order
x_original = t.rand((224, 224, 3 )) # [height, width, colour channels]

# permute the original tensor to rearrange the axis (or dim) order 

x_permuted = x_original.permute(2, 0, 1) # shift axis 
x_permuted.size() # [colour channels, height, width]

torch.Size([3, 224, 224])