In [1]:
import torch as t

### Indexing (selecting data from tensors)

In [2]:
t.manual_seed(23)
x = t.arange(1,10).reshape(1, 3, 3)
x, x.size()

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
# Use ":" to select all of the target dim
i_row, i_col  = 0, 1
print(x[:, i_row])  # = x[:, 0, :] 
print(x[:, :, i_col]) # get all of the 0th and 1st dim but only index 1 of 2nd dim. aka col 1

print(x[:, i_row, i_col]) # get all of the 0th dim but only the index 0 of 1st dim and the index 1 of the 2nd dim

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([2])



### Pytorch tensor & Numpy

* Data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor, to Numpy -> `torch.Tensor.numpy()`

In [4]:
import numpy as np

In [5]:
arr = np.arange(1.,8.)
tensor = t.from_numpy(arr).type(t.float32) # WARNING:  when convert np to tensor default dtype is float 64
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [6]:
# If we change the `arr`,will the `tensor` change?

arr = arr +1 
tensor # No, if separate dependently

tensor([1., 2., 3., 4., 5., 6., 7.])

In [7]:
# Tensor to numpy
tensor = t.ones(5)
numpy_arr = tensor.numpy()
numpy_arr.dtype, tensor

(dtype('float32'), tensor([1., 1., 1., 1., 1.]))

In [8]:
# If we change the `tensor`, Will the `numpy_arr` change?
tensor += 1
numpy_arr, tensor # It share memory

(array([2., 2., 2., 2., 2.], dtype=float32), tensor([2., 2., 2., 2., 2.]))

### Reproducibility (trying to take random out of random)
using `t.manual_seed(SEED)`

### set up device

In [9]:
t.cuda.is_available()

True

In [10]:
t.cuda.device_count()

1

In [11]:
DEVICE = "cuda" if t.cuda.is_available() else "cpu"
DEVICE

'cuda'

### Putting tensors on the GPU 

In [12]:
tensor = t.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [18]:
tensor_on_gpu = tensor.to(DEVICE)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [20]:
# Moving tensors back to the CPU

# If tensor is on GPU, can't transform it to Numpy
# tensor_on_gpu.numpy() # error

#to fix the GPU tensor with Numpy issue -> turn back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])